name: Deploy
on:
  workflow_run:
    workflows: ["run_unit_tests"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Push to deploy branch
        run: |
          git config --local user.email "vladleesi@outlook.com"
          git config --local user.name "vladleesi"
          git checkout -B release
          git pull origin master
          git push -f origin release
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Workflow was a failure"