name: Run unit tests
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: ./gradlew test